globalVariables(c('PostcodeArea',
                  'PostcodeArea_name',
                  'user_filter',
                  'total_filter',
                  'value',
                  'count',
                  'train_test',
                  '..response',
                  '..weight'))
